version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: R00tiest-
      MYSQL_DATABASE: springapp